# Generated by Django 2.2.7 on 2019-12-02 16:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quadrants',
            fields=[
                ('quadrant_no', models.IntegerField(primary_key=True, serialize=False)),
                ('quadrant_tx', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_no', models.IntegerField(primary_key=True, serialize=False)),
                ('quest_tx', models.CharField(default='', max_length=1000)),
                ('eval_tx', models.CharField(default='', max_length=1000)),
                ('evidence_tx', models.CharField(default='', max_length=1000)),
                ('results_tx', models.CharField(default='', max_length=1000)),
                ('rag_conditional_int', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('questionnaire_type_no', models.IntegerField(primary_key=True, serialize=False)),
                ('questionnaire_type_tx', models.CharField(default='', max_length=100)),
                ('completed_date_dt', models.DateField(default=datetime.date(2019, 12, 2))),
                ('quadrant_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social_value_app.Quadrants')),
            ],
        ),
        migrations.CreateModel(
            name='SME',
            fields=[
                ('company_id_no', models.IntegerField(primary_key=True, serialize=False)),
                ('SME_name_tx', models.CharField(default='', max_length=3000)),
                ('email_tx', models.CharField(default='', max_length=3000)),
                ('questionnaire_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social_value_app.Questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='quadrants',
            name='question_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social_value_app.Question'),
        ),
    ]
