# Generated by Django 2.2.7 on 2019-12-03 16:38

import datetime
from django.db import migrations, models
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Social_value_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quest_tx',
            field=pgcrypto.fields.TextPGPSymmetricKeyField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='completed_date_dt',
            field=models.DateField(default=datetime.date(2019, 12, 3)),
        ),
        migrations.AlterField(
            model_name='sme',
            name='SME_name_tx',
            field=pgcrypto.fields.TextPGPSymmetricKeyField(),
        ),
    ]
