# Generated by Django 2.2.7 on 2019-12-04 09:37

import datetime
from django.db import migrations, models
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Social_value_app', '0002_auto_20191203_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quest_tx',
            field=pgcrypto.fields.TextPGPSymmetricKeyField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='completed_date_dt',
            field=models.DateField(default=datetime.date(2019, 12, 4)),
        ),
    ]
