# Generated by Django 2.2.7 on 2019-12-04 09:48

import datetime
from django.db import migrations, models
import django.utils.timezone
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Social_value_app', '0002_auto_20191203_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quest_tx_hash',
            field=pgcrypto.fields.TextHMACField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='completed_date_dt',
            field=models.DateField(default=datetime.date(2019, 12, 4)),
        ),
    ]
