# Generated by Django 2.2.7 on 2019-12-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social_value_app', '0003_auto_20191204_0948'),
        ('Social_value_app', '0002_auto_20191203_1359'),
    ]

    operations = [
    ]
