# Generated by Django 2.2.7 on 2019-12-04 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_value_app', '0004_merge_20191204_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quest_tx_hash',
        ),
        migrations.AlterField(
            model_name='question',
            name='quest_tx',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='completed_date_dt',
            field=models.DateField(default=datetime.date(2019, 12, 4)),
        ),
    ]
