# Generated by Django 2.2.7 on 2019-12-05 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_value_app', '0005_auto_20191204_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='completed_date_dt',
            field=models.DateField(default=datetime.date(2019, 12, 5)),
        ),
    ]
